target-version = "py310"
select = [
    "F",    # Pyflakes
    "E",    # Pycodestyle
    "W",
    "I001", # isort
]
ignore = ["F401", "E402"]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]

line-length = 88

[pydocstyle]
convention = "google" # Accepts: "google", "numpy", or "pep257".
